version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb_daba:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
      MARIADB_USER: user
      MARIADB_PASSWORD: user
  keycloak:
    container_name: keycloakInstance
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8180:8080"
    command: start-dev

  activemq:
    image: islandora/activemq:renovate.islandora-starter-site-digest
    container_name: activemq
    ports:
      - "61616:61616" # JMS port
      - "8161:8161"   # Web UI port
  producer:
    build: ./producer
    depends_on:
      - activemq
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    ports:
      - "8082:8082"
  consumer:
    build: ./consumer
    depends_on:
      - activemq
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/testdb
    ports:
      - "8083:8083"

volumes:
  mariadb_daba:
  keycloak_data: